kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: substrate-telemetry
  name: backend-core
  labels:
    app: backend-core
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-core
  template:
    metadata:
      labels:
        app: backend-core
    spec:
      containers:
        - name: backend-core
          image: ghcr.io/envops-git/substrate-telemetry:master-backend
          command: ['telemetry_core', '--listen', '0.0.0.0:8000']
          ports:
            - containerPort: 8000


---
apiVersion: v1
kind: Service
metadata:
  name: backend-core
  namespace: substrate-telemetry
  labels:
    app: backend-core
spec:
  ports:
  - port: 8000
    name: backend-core
  selector:
    app: backend-core

